//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace LibSESAR_CSharp.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public partial class samples
    {

        private samplesSample[] sampleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample")]
        public samplesSample[] sample
        {
            get
            {
                return this.sampleField;
            }
            set
            {
                this.sampleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    public partial class samplesSample
    {

        private string user_codeField;

        private sample_type sample_typeField;

        private string nameField;

        private material materialField;

        private string igsnField;

        private string parent_igsnField;

        private is_private is_privateField;

        private bool is_privateFieldSpecified;

        private string publish_dateField;

        private string classificationField;

        private string classification_commentField;

        private string field_nameField;

        private string descriptionField;

        private decimal age_minField;

        private bool age_minFieldSpecified;

        private decimal age_maxField;

        private bool age_maxFieldSpecified;

        private string age_unitField;

        private string geological_ageField;

        private string geological_unitField;

        private string collection_methodField;

        private string collection_method_descrField;

        private string sizeField;

        private string size_unitField;

        private string sample_commentField;

        private string purposeField;

        private decimal latitudeField;

        private bool latitudeFieldSpecified;

        private decimal longitudeField;

        private bool longitudeFieldSpecified;

        private decimal latitude_endField;

        private bool latitude_endFieldSpecified;

        private decimal longitude_endField;

        private bool longitude_endFieldSpecified;

        private decimal elevationField;

        private bool elevationFieldSpecified;

        private decimal elevation_endField;

        private bool elevation_endFieldSpecified;

        private elevation_unit elevation_unitField;

        private bool elevation_unitFieldSpecified;

        private vertical_datum vertical_datumField;

        private bool vertical_datumFieldSpecified;

        private decimal northingField;

        private bool northingFieldSpecified;

        private decimal eastingField;

        private bool eastingFieldSpecified;

        private string zoneField;

        private navigation_type navigation_typeField;

        private bool navigation_typeFieldSpecified;

        private string primary_location_typeField;

        private string primary_location_nameField;

        private string location_descriptionField;

        private string localityField;

        private string locality_descriptionField;

        private string countryField;

        private string provinceField;

        private string countyField;

        private string cityField;

        private string cruise_field_prgrmField;

        private string platform_typeField;

        private string platform_nameField;

        private string platform_descrField;

        private string launch_platform_nameField;

        private string launch_idField;

        private launch_type_name launch_type_nameField;

        private bool launch_type_nameFieldSpecified;

        private string collectorField;

        private string collector_detailField;

        private System.DateTime collection_start_dateField;

        private bool collection_start_dateFieldSpecified;

        private System.DateTime collection_end_dateField;

        private bool collection_end_dateFieldSpecified;

        private collection_date_precision collection_date_precisionField;

        private bool collection_date_precisionFieldSpecified;

        private string current_archiveField;

        private string current_archive_contactField;

        private string original_archiveField;

        private string original_archive_contactField;

        private decimal depth_minField;

        private bool depth_minFieldSpecified;

        private decimal depth_maxField;

        private bool depth_maxFieldSpecified;

        private string depth_scaleField;

        private string[] sample_other_namesField;

        private samplesSampleExternal_url[] external_urlsField;

        public samplesSample()
        {
            this.is_privateField = is_private.Item0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string user_code
        {
            get
            {
                return this.user_codeField;
            }
            set
            {
                this.user_codeField = value;
            }
        }

        /// <remarks/>
        public sample_type sample_type
        {
            get
            {
                return this.sample_typeField;
            }
            set
            {
                this.sample_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public material material
        {
            get
            {
                return this.materialField;
            }
            set
            {
                this.materialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string igsn
        {
            get
            {
                return this.igsnField;
            }
            set
            {
                this.igsnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string parent_igsn
        {
            get
            {
                return this.parent_igsnField;
            }
            set
            {
                this.parent_igsnField = value;
            }
        }

        /// <remarks/>
        public is_private is_private
        {
            get
            {
                return this.is_privateField;
            }
            set
            {
                this.is_privateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_privateSpecified
        {
            get
            {
                return this.is_privateFieldSpecified;
            }
            set
            {
                this.is_privateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string publish_date
        {
            get
            {
                return this.publish_dateField;
            }
            set
            {
                this.publish_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string classification
        {
            get
            {
                return this.classificationField;
            }
            set
            {
                this.classificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string classification_comment
        {
            get
            {
                return this.classification_commentField;
            }
            set
            {
                this.classification_commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string field_name
        {
            get
            {
                return this.field_nameField;
            }
            set
            {
                this.field_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public decimal age_min
        {
            get
            {
                return this.age_minField;
            }
            set
            {
                this.age_minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool age_minSpecified
        {
            get
            {
                return this.age_minFieldSpecified;
            }
            set
            {
                this.age_minFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal age_max
        {
            get
            {
                return this.age_maxField;
            }
            set
            {
                this.age_maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool age_maxSpecified
        {
            get
            {
                return this.age_maxFieldSpecified;
            }
            set
            {
                this.age_maxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string age_unit
        {
            get
            {
                return this.age_unitField;
            }
            set
            {
                this.age_unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string geological_age
        {
            get
            {
                return this.geological_ageField;
            }
            set
            {
                this.geological_ageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string geological_unit
        {
            get
            {
                return this.geological_unitField;
            }
            set
            {
                this.geological_unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string collection_method
        {
            get
            {
                return this.collection_methodField;
            }
            set
            {
                this.collection_methodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string collection_method_descr
        {
            get
            {
                return this.collection_method_descrField;
            }
            set
            {
                this.collection_method_descrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string size_unit
        {
            get
            {
                return this.size_unitField;
            }
            set
            {
                this.size_unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string sample_comment
        {
            get
            {
                return this.sample_commentField;
            }
            set
            {
                this.sample_commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }

        /// <remarks/>
        public decimal latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudeSpecified
        {
            get
            {
                return this.latitudeFieldSpecified;
            }
            set
            {
                this.latitudeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudeSpecified
        {
            get
            {
                return this.longitudeFieldSpecified;
            }
            set
            {
                this.longitudeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal latitude_end
        {
            get
            {
                return this.latitude_endField;
            }
            set
            {
                this.latitude_endField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitude_endSpecified
        {
            get
            {
                return this.latitude_endFieldSpecified;
            }
            set
            {
                this.latitude_endFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal longitude_end
        {
            get
            {
                return this.longitude_endField;
            }
            set
            {
                this.longitude_endField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitude_endSpecified
        {
            get
            {
                return this.longitude_endFieldSpecified;
            }
            set
            {
                this.longitude_endFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal elevation
        {
            get
            {
                return this.elevationField;
            }
            set
            {
                this.elevationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool elevationSpecified
        {
            get
            {
                return this.elevationFieldSpecified;
            }
            set
            {
                this.elevationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal elevation_end
        {
            get
            {
                return this.elevation_endField;
            }
            set
            {
                this.elevation_endField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool elevation_endSpecified
        {
            get
            {
                return this.elevation_endFieldSpecified;
            }
            set
            {
                this.elevation_endFieldSpecified = value;
            }
        }

        /// <remarks/>
        public elevation_unit elevation_unit
        {
            get
            {
                return this.elevation_unitField;
            }
            set
            {
                this.elevation_unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool elevation_unitSpecified
        {
            get
            {
                return this.elevation_unitFieldSpecified;
            }
            set
            {
                this.elevation_unitFieldSpecified = value;
            }
        }

        /// <remarks/>
        public vertical_datum vertical_datum
        {
            get
            {
                return this.vertical_datumField;
            }
            set
            {
                this.vertical_datumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vertical_datumSpecified
        {
            get
            {
                return this.vertical_datumFieldSpecified;
            }
            set
            {
                this.vertical_datumFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal northing
        {
            get
            {
                return this.northingField;
            }
            set
            {
                this.northingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool northingSpecified
        {
            get
            {
                return this.northingFieldSpecified;
            }
            set
            {
                this.northingFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal easting
        {
            get
            {
                return this.eastingField;
            }
            set
            {
                this.eastingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eastingSpecified
        {
            get
            {
                return this.eastingFieldSpecified;
            }
            set
            {
                this.eastingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }

        /// <remarks/>
        public navigation_type navigation_type
        {
            get
            {
                return this.navigation_typeField;
            }
            set
            {
                this.navigation_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool navigation_typeSpecified
        {
            get
            {
                return this.navigation_typeFieldSpecified;
            }
            set
            {
                this.navigation_typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string primary_location_type
        {
            get
            {
                return this.primary_location_typeField;
            }
            set
            {
                this.primary_location_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string primary_location_name
        {
            get
            {
                return this.primary_location_nameField;
            }
            set
            {
                this.primary_location_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string location_description
        {
            get
            {
                return this.location_descriptionField;
            }
            set
            {
                this.location_descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string locality_description
        {
            get
            {
                return this.locality_descriptionField;
            }
            set
            {
                this.locality_descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string province
        {
            get
            {
                return this.provinceField;
            }
            set
            {
                this.provinceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string county
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string cruise_field_prgrm
        {
            get
            {
                return this.cruise_field_prgrmField;
            }
            set
            {
                this.cruise_field_prgrmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string platform_type
        {
            get
            {
                return this.platform_typeField;
            }
            set
            {
                this.platform_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string platform_name
        {
            get
            {
                return this.platform_nameField;
            }
            set
            {
                this.platform_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string platform_descr
        {
            get
            {
                return this.platform_descrField;
            }
            set
            {
                this.platform_descrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string launch_platform_name
        {
            get
            {
                return this.launch_platform_nameField;
            }
            set
            {
                this.launch_platform_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string launch_id
        {
            get
            {
                return this.launch_idField;
            }
            set
            {
                this.launch_idField = value;
            }
        }

        /// <remarks/>
        public launch_type_name launch_type_name
        {
            get
            {
                return this.launch_type_nameField;
            }
            set
            {
                this.launch_type_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool launch_type_nameSpecified
        {
            get
            {
                return this.launch_type_nameFieldSpecified;
            }
            set
            {
                this.launch_type_nameFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string collector
        {
            get
            {
                return this.collectorField;
            }
            set
            {
                this.collectorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string collector_detail
        {
            get
            {
                return this.collector_detailField;
            }
            set
            {
                this.collector_detailField = value;
            }
        }

        /// <remarks/>
        public System.DateTime collection_start_date
        {
            get
            {
                return this.collection_start_dateField;
            }
            set
            {
                this.collection_start_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool collection_start_dateSpecified
        {
            get
            {
                return this.collection_start_dateFieldSpecified;
            }
            set
            {
                this.collection_start_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime collection_end_date
        {
            get
            {
                return this.collection_end_dateField;
            }
            set
            {
                this.collection_end_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool collection_end_dateSpecified
        {
            get
            {
                return this.collection_end_dateFieldSpecified;
            }
            set
            {
                this.collection_end_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public collection_date_precision collection_date_precision
        {
            get
            {
                return this.collection_date_precisionField;
            }
            set
            {
                this.collection_date_precisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool collection_date_precisionSpecified
        {
            get
            {
                return this.collection_date_precisionFieldSpecified;
            }
            set
            {
                this.collection_date_precisionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string current_archive
        {
            get
            {
                return this.current_archiveField;
            }
            set
            {
                this.current_archiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string current_archive_contact
        {
            get
            {
                return this.current_archive_contactField;
            }
            set
            {
                this.current_archive_contactField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string original_archive
        {
            get
            {
                return this.original_archiveField;
            }
            set
            {
                this.original_archiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string original_archive_contact
        {
            get
            {
                return this.original_archive_contactField;
            }
            set
            {
                this.original_archive_contactField = value;
            }
        }

        /// <remarks/>
        public decimal depth_min
        {
            get
            {
                return this.depth_minField;
            }
            set
            {
                this.depth_minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool depth_minSpecified
        {
            get
            {
                return this.depth_minFieldSpecified;
            }
            set
            {
                this.depth_minFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal depth_max
        {
            get
            {
                return this.depth_maxField;
            }
            set
            {
                this.depth_maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool depth_maxSpecified
        {
            get
            {
                return this.depth_maxFieldSpecified;
            }
            set
            {
                this.depth_maxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string depth_scale
        {
            get
            {
                return this.depth_scaleField;
            }
            set
            {
                this.depth_scaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("sample_other_name", DataType = "token", IsNullable = false)]
        public string[] sample_other_names
        {
            get
            {
                return this.sample_other_namesField;
            }
            set
            {
                this.sample_other_namesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("external_url", IsNullable = false)]
        public samplesSampleExternal_url[] external_urls
        {
            get
            {
                return this.external_urlsField;
            }
            set
            {
                this.external_urlsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum sample_type
    {

        /// <remarks/>
        Bead,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Chemical Fraction")]
        ChemicalFraction,

        /// <remarks/>
        Core,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Core Half Round")]
        CoreHalfRound,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Core Piece")]
        CorePiece,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Core Quarter Round")]
        CoreQuarterRound,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Core Section")]
        CoreSection,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Core Section Half")]
        CoreSectionHalf,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Core Sub-Piece")]
        CoreSubPiece,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Core Whole Round")]
        CoreWholeRound,

        /// <remarks/>
        CTD,

        /// <remarks/>
        Cube,

        /// <remarks/>
        Culture,

        /// <remarks/>
        Cuttings,

        /// <remarks/>
        Cylinder,

        /// <remarks/>
        Dredge,

        /// <remarks/>
        Gas,

        /// <remarks/>
        Grab,

        /// <remarks/>
        Hole,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Individual Sample")]
        IndividualSample,

        /// <remarks/>
        Liquid,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mechanical Fraction")]
        MechanicalFraction,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Oriented Core")]
        OrientedCore,

        /// <remarks/>
        Powder,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Rock Powder")]
        RockPowder,

        /// <remarks/>
        Site,

        /// <remarks/>
        Slab,

        /// <remarks/>
        Smear,

        /// <remarks/>
        Specimen,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Squeeze Cake")]
        SqueezeCake,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Terrestrial Section")]
        TerrestrialSection,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Thin Section")]
        ThinSection,

        /// <remarks/>
        Toothpick,

        /// <remarks/>
        Trawl,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("U-Channel")]
        UChannel,

        /// <remarks/>
        Wedge,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum material
    {

        /// <remarks/>
        Biology,

        /// <remarks/>
        Gas,

        /// <remarks/>
        Ice,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Liquid>aqueous")]
        Liquidaqueous,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Liquid>organic")]
        Liquidorganic,

        /// <remarks/>
        Mineral,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not applicable")]
        Notapplicable,

        /// <remarks/>
        Other,

        /// <remarks/>
        Particulate,

        /// <remarks/>
        Rock,

        /// <remarks/>
        Sediment,

        /// <remarks/>
        Soil,

        /// <remarks/>
        Synthetic,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum is_private
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum elevation_unit
    {

        /// <remarks/>
        Feet,

        /// <remarks/>
        Meters,

        /// <remarks/>
        Kilometers,

        /// <remarks/>
        Miles,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum vertical_datum
    {

        /// <remarks/>
        NAVD88,

        /// <remarks/>
        MSL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum navigation_type
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ACOUSTIC_RANGING/GPS")]
        ACOUSTIC_RANGINGGPS,

        /// <remarks/>
        DGPS,

        /// <remarks/>
        DVL,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DVL/LBL")]
        DVLLBL,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DVL/LBL/INS")]
        DVLLBLINS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DVL/LBL:Renav")]
        DVLLBLRenav,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DVL/LBL:Renav:Confirmed")]
        DVLLBLRenavConfirmed,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DVL/USBL")]
        DVLUSBL,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DVL/USBL:Renav")]
        DVLUSBLRenav,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DVL:Renav")]
        DVLRenav,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DVL:Renav:Confirmed")]
        DVLRenavConfirmed,

        /// <remarks/>
        GLONASS,

        /// <remarks/>
        GPS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GPS/WireOut")]
        GPSWireOut,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GPS:Assumed")]
        GPSAssumed,

        /// <remarks/>
        LAYBACK,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LAYBACK/LBL")]
        LAYBACKLBL,

        /// <remarks/>
        LBL,

        /// <remarks/>
        LORAN,

        /// <remarks/>
        Locale,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not Applicable")]
        NotApplicable,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("RTK GPS")]
        RTKGPS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum launch_type_name
    {

        /// <remarks/>
        AUV,

        /// <remarks/>
        HOV,

        /// <remarks/>
        ROV,

        /// <remarks/>
        Sled,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not Applicable")]
        NotApplicable,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum collection_date_precision
    {

        /// <remarks/>
        year,

        /// <remarks/>
        month,

        /// <remarks/>
        day,

        /// <remarks/>
        time,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    public partial class samplesSampleExternal_url
    {

        private string urlField;

        private string descriptionField;

        private url_type url_typeField;

        private bool url_typeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public url_type url_type
        {
            get
            {
                return this.url_typeField;
            }
            set
            {
                this.url_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool url_typeSpecified
        {
            get
            {
                return this.url_typeFieldSpecified;
            }
            set
            {
                this.url_typeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://app.geosamples.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://app.geosamples.org", IsNullable = false)]
    public enum url_type
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("regular URL")]
        regularURL,

        /// <remarks/>
        DOI,
    }
}